import { test, expect } from '@playwright/test';
import { readFile, writeFile, mkdtemp, rm } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { unzipSync } from 'fflate';
import { createHash } from 'node:crypto';
let fixtureDirectory:string;
let loopFixture:string;
test.beforeAll(async()=>{ fixtureDirectory=await mkdtemp(join(tmpdir(),'drift-video-test-')); loopFixture=join(fixtureDirectory,'loop.mp4'); execFileSync('ffmpeg',['-hide_banner','-loglevel','error','-f','lavfi','-i','testsrc2=size=320x180:rate=24:duration=1','-c:v','libx264','-pix_fmt','yuv420p','-g','12','-an',loopFixture]); });
test.afterAll(async()=>{if(fixtureDirectory)await rm(fixtureDirectory,{recursive:true,force:true});});
import { fixturePath, presenterFixturePath, waitForStudio, switchWorkspace } from './studio.helpers';

test('video slide import, looping, media undo, and portable reopen preserve originals', async ({page}) => {
  const errors:string[]=[];
  page.on('pageerror',e=>errors.push(e.message));
  await waitForStudio(page);
  await page.locator('input[type=file][multiple]').setInputFiles([fixturePath,presenterFixturePath]);
  await expect(page.locator('.asset-list li')).toHaveCount(2);
  await expect(page.locator('.header-status')).toContainText('saved locally');
  const video=page.locator('.asset-list li').filter({hasText:'presenter.mp4'});
  await video.locator('.asset-select').click();
  await switchWorkspace(page,'SLIDES');
  const loop=page.getByRole('switch',{name:'Loop video'});
  await expect(loop).toBeVisible();
  await expect(loop).toBeChecked();
  await loop.click();
  await expect(loop).not.toBeChecked();
  await video.getByRole('button',{name:'Remove presenter.mp4',exact:true}).click();
  await video.getByRole('button',{name:'Confirm removal of presenter.mp4',exact:true}).click();
  await expect(page.locator('.asset-list li')).toHaveCount(1);
  await page.locator('.stage-topline').first().click();
  await page.keyboard.press('Control+z');
  await expect(page.locator('.asset-list li')).toHaveCount(2);
  await switchWorkspace(page,'EXPORT');
  const download=page.waitForEvent('download');
  await page.getByRole('button',{name:'Save portable project',exact:true}).click();
  const saved=await download;
  const path=await saved.path();
  expect(path).toBeTruthy();
  const archive=unzipSync(new Uint8Array(await readFile(path!)));
  const original=await readFile(presenterFixturePath);
  const manifest=JSON.parse(new TextDecoder().decode(archive['manifest.json']!));
  const item=manifest.assets.find((entry:{name:string})=>entry.name==='presenter.mp4');
  expect(item).toBeTruthy();
  expect(Buffer.from(archive[item.path]!)).toEqual(original);
  expect(createHash('sha256').update(original).digest('hex')).toBe(item.sha256);
  const chooser=page.waitForEvent('filechooser');
  await page.getByRole('button',{name:'Open project',exact:true}).click();
  await (await chooser).setFiles(path!);
  await expect(page.locator('.header-status')).toContainText('saved locally');
  await page.reload();
  await expect(page.locator('.asset-list li')).toHaveCount(2);
  await page.locator('.asset-list li').filter({hasText:'presenter.mp4'}).locator('.asset-select').click();
  await switchWorkspace(page,'SLIDES');
  await expect(loop).not.toBeChecked();
  expect(errors).toEqual([]);
});

test('real video loops sample identical source frames and produces a decoded MP4',async({page},testInfo)=>{
  await page.goto('/');
  const encoded=(await readFile(loopFixture)).toString('base64');
  const receipt=await page.evaluate(async(encoded)=>{
    const [{CinematicCarousel},{DEFAULT_SETTINGS},{exportMp4},{videoFileToAsset}]=await Promise.all([
      import('/src/engine/CinematicCarousel.ts'),import('/src/model.ts'),import('/src/lib/exportStudio.ts'),import('/src/lib/assets.ts')]);
    const asset=await videoFileToAsset(new File([Uint8Array.from(atob(encoded),c=>c.charCodeAt(0))],'loop.mp4',{type:'video/mp4'}));
    const settings=structuredClone(DEFAULT_SETTINGS);
    settings.stage={width:320,height:320,transparent:false};
    settings.background={...settings.background,style:"solid",grain:0,vignette:0,motion:0};
    settings.output={...settings.output,width:320,height:320,fps:24,duration:asset.duration!*2};
    settings.motion={...settings.motion,axis:'horizontal',speed:0,flow:'straight',gap:0,curvature:0,depth:0,tilt:0,distortion:0,focusScale:0,edgeFade:0};
    settings.slide={...settings.slide,aspectWidth:1,aspectHeight:1,scale:1,fit:'cover',radius:0,borderWidth:0,shadowOpacity:0};
    const canvas=document.createElement('canvas');document.body.append(canvas);
    const engine=new CinematicCarousel(canvas,{kind:'v1-compat',settings});
    try {
      await engine.setAssets([asset]);
      const surface=engine.beginExport(320,320);
      const sample=async(time:number)=>{await engine.renderAtAsync(time);const c=document.createElement('canvas');c.width=32;c.height=32;const ctx=c.getContext('2d')!;ctx.drawImage(canvas,0,0,32,32);return Array.from(ctx.getImageData(0,0,32,32).data);};
      const a=await sample(0.25),b=await sample(asset.duration!+0.25),c=await sample(0.75);
      const difference=(a:number[],b:number[])=>a.reduce((sum,x,i)=>sum+Math.abs(x-b[i]!),0);
      const exported=await exportMp4({canvas,renderAt:async(t,_p,ctx)=>{await engine.renderAtAsync(t,ctx?.frameIndex,ctx?.signal); if(ctx?.frameIndex===ctx!.frameCount-1)engine.releaseVideoSlideDecoders();},settings:{width:320,height:320,fps:24,duration:asset.duration!*2},includePresenterAudio:false});
      surface.restore();
      const bytes= new Uint8Array(await exported.blob!.arrayBuffer());
      let raw=""; for(let i=0;i<bytes.length;i+=8192)raw+=String.fromCharCode(...bytes.subarray(i,i+8192));
      return {artifact:btoa(raw),loopDifference:difference(a,b),movingDifference:difference(a,c),bytes:exported.blob?.size,verification:exported.verification,duration:asset.duration};
    }finally {engine.dispose();URL.revokeObjectURL(asset.objectUrl);canvas.remove();}
  },encoded);
  const output=testInfo.outputPath('synthetic-video-loop.mp4');
  await writeFile(output,Buffer.from(receipt.artifact,'base64'));
  const inspected=JSON.parse(execFileSync('ffprobe',['-v','error','-count_frames','-show_streams','-of','json',output],{encoding:'utf8'}));
  const track=inspected.streams.find((stream:{codec_type:string})=>stream.codec_type==='video');
  expect(track.width).toBe(320); expect(track.height).toBe(320);
  expect(Number(track.nb_read_frames)).toBe(48);
  expect(inspected.streams.some((stream:{codec_type:string})=>stream.codec_type==='audio')).toBe(false);
  const frames=execFileSync('ffmpeg',['-v','error','-i',output,'-vf','select=eq(n\\,6)+eq(n\\,30)','-vsync','0','-f','rawvideo','-pix_fmt','rgb24','pipe:1'],{maxBuffer:1024*1024});
  expect(frames.length).toBe(320*320*3*2);
  let error=0;for(let i=0;i<320*320*3;i++)error+=Math.abs(frames[i]!-frames[i+320*320*3]!);
  expect(error/(320*320*3)).toBeLessThan(8);
  await testInfo.attach('synthetic-video-loop',{path:output,contentType:'video/mp4'});
  expect(receipt.loopDifference).toBe(0);
  expect(receipt.movingDifference).toBeGreaterThan(100);
  expect(receipt.bytes).toBeGreaterThan(1000);
  expect(receipt.verification.verified).toBe(true);
  expect(receipt.verification.frameCount).toBe(Math.floor(receipt.duration!*2*24));
});
