import {
  DRIFT_PROJECT_SCHEMA,
  DRIFT_PROJECT_VERSION,
  PROJECT_DOMAINS,
  type DriftProjectV3,
  type RecipeProvenance,
} from "./schema";

export function createEmptyRecipeProvenance(): RecipeProvenance {
  return {
    world: null,
    worldVariant: "custom",
    recipes: Object.fromEntries(PROJECT_DOMAINS.map((domain) => [domain, null])) as RecipeProvenance["recipes"],
    lockedDomains: [],
  };
}

export function createDefaultDriftProject(
  projectId: string,
  now = new Date().toISOString(),
  projectSeed = 17,
): DriftProjectV3 {
  return {
    schema: DRIFT_PROJECT_SCHEMA,
    formatVersion: DRIFT_PROJECT_VERSION,
    projectId,
    projectSeed,
    createdAt: now,
    updatedAt: now,
    composition: {
      width: 1080,
      height: 1920,
      alphaMode: "opaque",
      colourSpace: "srgb-rec709",
    },
    media: {
      order: [],
      presenterAssetId: null,
      assets: {},
    },
    slides: {},
    motion: {
      transport: {
        axis: "vertical",
        direction: -1,
        slidesPerSecond: 0.34,
      },
      cadence: {
        cutId: "paper-argument",
        read: 0.22,
        anticipation: 0.08,
        carry: 0.42,
        impact: 0.08,
        settle: 0.1,
        land: 0.1,
        poseCadence: "continuous",
      },
      performance: {
        id: "long-take",
        weight: 0.72,
        linger: 0.48,
        release: 0.72,
        runway: 1,
        overlap: 0.22,
        imperfection: 0.04,
        take: 1,
      },
      character: {
        id: "weighted",
        amount: 0.72,
      },
      path: {
        id: "ribbon",
        gap: 0.22,
        curvature: 0.36,
        depth: 0.18,
        banking: 4.5,
        focusScale: 0.08,
        edgeFade: 0.28,
      },
      seamless: {
        enabled: false,
        loops: 1,
      },
    },
    card: {
      aspectWidth: 16,
      aspectHeight: 9,
      scale: 0.78,
      defaultFit: "cover",
      radius: 36,
      smoothing: 0.6,
      borderWidth: 0,
      borderColor: "#f0e6d4",
      borderOpacity: 0,
    },
    material: {
      surface: "card",
      flex: 0.18,
      thickness: 0,
      roughness: 0.76,
      sheen: 0.06,
      finish: {
        id: "clean-glass",
        registration: 0,
        localSoftness: 0,
        localSmear: 0,
        microtexture: 0.04,
      },
    },
    lighting: {
      enabled: true,
      presetId: "studio-soft",
      space: "stage",
      motionMode: "breathe",
      motionSpeed: 1,
      keyColor: "#fff1dc",
      fillColor: "#b9c9e8",
      shadowColor: "#100c12",
      azimuth: 42,
      elevation: 56,
      keyIntensity: 0.78,
      fillIntensity: 0.54,
      rimIntensity: 0.14,
      artworkProtection: 0.82,
      heroProtection: 0.82,
      shadowOpacity: 0.34,
      shadowSoftness: 52,
      shadowDistance: 54,
      contactStrength: 0.58,
      backgroundSpill: 0.28,
      spillFocus: 0.78,
      gobo: "softbox",
      goboStrength: 0.08,
      breath: 0.1,
    },
    atmosphere: {
      enabled: true,
      family: "aura",
      composition: "orbiting-bloom",
      paletteId: "tungsten-archive",
      treatment: "cinema",
      recut: 0,
      seedOffset: projectSeed,
      presence: "balanced",
      intensity: 0.72,
      motion: 0.22,
      grain: 0.06,
      vignette: 0.46,
      colourA: "#120f0c",
      colourB: "#2c1516",
      accent: "#c26d3f",
    },
    lens: {
      enabled: true,
      characterId: "clean-gate",
      presence: 0.16,
      focus: 0.02,
      directionalSmear: 0.05,
      chromaticSeparation: 0.015,
      bloom: 0.015,
      halation: 0.01,
      flare: 0,
      curvature: 0,
      gateWeave: 0,
      cameraGrain: 0.035,
      vignette: 0.04,
      presenterTreatment: "protected",
    },
    sound: {
      source: "recorded",
      material: "studio",
      grammar: "dry",
      density: 0.42,
      texture: 0.28,
      take: 1,
      masterLevel: 0.72,
      motionLevel: 0.5,
      interfaceLevel: 0.28,
      underVoice: 0.36,
      previewEnabled: false,
      exportEnabled: false,
    },
    presenter: {
      enabled: false,
      x: 0.72,
      y: 0.28,
      width: 0.34,
      aspectWidth: 9,
      aspectHeight: 16,
      fit: "cover",
      radius: 42,
      smoothing: 0.6,
      borderWidth: 0,
      borderColor: "#f4ead8",
      borderOpacity: 0,
      muted: false,
      gain: 1,
      trimStart: 0,
      startAt: 0,
    },
    master: {
      fps: 30,
      duration: 8,
      reducedMotion: false,
      video: {
        format: "h264",
        bitrate: 16_000_000,
      },
      audio: {
        enabled: false,
        bitrate: 192_000,
      },
    },
    provenance: createEmptyRecipeProvenance(),
  };
}
