import { getBackgroundScene, type BackgroundSceneId } from "./backgrounds";
import { DEFAULT_SETTINGS, type StudioSettings, type ThemeId } from "./model";

export interface ThemePreset {
  id: ThemeId;
  name: string;
  eyebrow: string;
  description: string;
  settings: StudioSettings;
}

function makeTheme(
  id: ThemeId,
  name: string,
  eyebrow: string,
  description: string,
  sceneId: BackgroundSceneId,
  patch: {
    motion?: Partial<StudioSettings["motion"]>;
    slide?: Partial<StudioSettings["slide"]>;
    background?: Partial<StudioSettings["background"]>;
  },
): ThemePreset {
  const scene = getBackgroundScene(sceneId);
  return {
    id,
    name,
    eyebrow,
    description,
    settings: {
      ...structuredClone(DEFAULT_SETTINGS),
      themeId: id,
      motion: { ...DEFAULT_SETTINGS.motion, ...patch.motion },
      slide: { ...DEFAULT_SETTINGS.slide, ...patch.slide },
      background: { ...scene.settings, ...patch.background },
    },
  };
}

export const THEMES: ThemePreset[] = [
  makeTheme(
    "editorial-drift",
    "Editorial Drift",
    "Long breath · warm projector",
    "Measured vertical rhythm. Slides arrive like pages crossing a dim projector gate.",
    "projector-bloom",
    {
      motion: {
        axis: "vertical",
        direction: -1,
        speed: 0.34,
        flow: "ribbon",
        curvature: 0.36,
        depth: 0.18,
        tilt: 4.5,
        distortion: 0.34,
        edgeFade: 0.28,
        focusScale: 0.08,
      },
      slide: {
        scale: 0.78,
        radius: 36,
        smoothing: 0.6,
        borderColor: "#f0e6d4",
        borderOpacity: 0.42,
        shadowOpacity: 0.36,
        shadowSoftness: 38,
      },
    },
  ),
  makeTheme(
    "road-memory",
    "Road Memory",
    "Travel · sun-struck lateral",
    "A wide, unhurried procession with heat-haze bend and a distant sodium horizon.",
    "sodium-horizon",
    {
      motion: {
        axis: "horizontal",
        direction: -1,
        speed: 0.28,
        flow: "arc",
        gap: 0.3,
        curvature: 0.46,
        depth: 0.28,
        tilt: 2.2,
        distortion: 0.24,
        edgeFade: 0.24,
      },
      slide: {
        scale: 0.72,
        radius: 28,
        borderColor: "#f7dfbd",
        borderOpacity: 0.5,
        shadowOpacity: 0.24,
      },
    },
  ),
  makeTheme(
    "dread",
    "Dread",
    "Horror · upward unease",
    "Slow vertical crawl, smoke-lit depth, and an optical response that tightens under movement.",
    "ember-fog",
    {
      motion: {
        axis: "vertical",
        direction: -1,
        speed: 0.17,
        flow: "tunnel",
        gap: 0.44,
        curvature: 0.72,
        depth: 0.56,
        tilt: 8.5,
        distortion: 0.78,
        focusScale: 0.04,
        edgeFade: 0.5,
      },
      slide: {
        scale: 0.73,
        radius: 18,
        smoothing: 0.18,
        borderColor: "#9d302b",
        borderOpacity: 0.66,
        shadowOpacity: 0.62,
        shadowSoftness: 48,
      },
    },
  ),
  makeTheme(
    "noir-contact",
    "Noir Contact",
    "Documentary · hard evidence",
    "A disciplined contact sheet: silver-gelatin texture, exact pace, and almost no optical melodrama.",
    "silver-gelatin",
    {
      motion: {
        axis: "horizontal",
        direction: 1,
        speed: 0.42,
        flow: "straight",
        gap: 0.16,
        curvature: 0,
        depth: 0.08,
        tilt: 0.8,
        distortion: 0.08,
        focusScale: 0.02,
        edgeFade: 0.1,
      },
      slide: {
        scale: 0.66,
        radius: 6,
        smoothing: 0,
        borderWidth: 3,
        borderColor: "#e9e5dc",
        borderOpacity: 0.9,
        shadowOpacity: 0.18,
        shadowSoftness: 24,
      },
    },
  ),
  makeTheme(
    "tender-light",
    "Tender Light",
    "Romance · soft orbit",
    "Close, luminous movement with rose light, softened edges, and almost-touching frames.",
    "rose-chamber",
    {
      motion: {
        axis: "horizontal",
        direction: -1,
        speed: 0.2,
        flow: "ribbon",
        gap: 0.08,
        curvature: 0.28,
        depth: 0.14,
        tilt: 2.8,
        distortion: 0.56,
        focusScale: 0.13,
        edgeFade: 0.42,
      },
      slide: {
        scale: 0.8,
        radius: 54,
        smoothing: 0.78,
        borderColor: "#ffe9dc",
        borderOpacity: 0.52,
        shadowOpacity: 0.26,
        shadowSoftness: 58,
      },
    },
  ),
  makeTheme(
    "chrome-dream",
    "Chrome Dream",
    "Music · electric tunnel",
    "Fast metallic depth and ultraviolet atmosphere without allowing the effect to eat the slide.",
    "liquid-chrome",
    {
      motion: {
        axis: "horizontal",
        direction: -1,
        speed: 0.58,
        flow: "cylinder",
        gap: 0.26,
        curvature: 0.68,
        depth: 0.48,
        tilt: 9,
        distortion: 0.72,
        focusScale: 0.14,
        edgeFade: 0.4,
      },
      slide: {
        scale: 0.62,
        radius: 32,
        smoothing: 0.62,
        borderColor: "#cfe8ff",
        borderOpacity: 0.7,
        shadowOpacity: 0.5,
        shadowSoftness: 34,
      },
    },
  ),
  makeTheme(
    "archive-fever",
    "Archive Fever",
    "History · found material",
    "A low horizontal scan through dust, imperfect exposure, and frames that feel handled rather than filtered.",
    "archive-dust",
    {
      motion: {
        axis: "horizontal",
        direction: 1,
        speed: 0.24,
        flow: "ribbon",
        gap: 0.12,
        curvature: 0.2,
        depth: 0.12,
        tilt: 3.5,
        distortion: 0.3,
        focusScale: 0.05,
        edgeFade: 0.34,
      },
      slide: {
        scale: 0.7,
        radius: 8,
        smoothing: 0.08,
        borderWidth: 4,
        borderColor: "#d2bf95",
        borderOpacity: 0.72,
        shadowOpacity: 0.32,
        shadowSoftness: 28,
      },
    },
  ),
  makeTheme(
    "neon-motel",
    "Neon Motel",
    "Thriller · wet midnight",
    "Rain-softened lateral movement, motel colour, and a nervous fringe that wakes only when the strip moves.",
    "after-rain",
    {
      motion: {
        axis: "horizontal",
        direction: -1,
        speed: 0.36,
        flow: "arc",
        gap: 0.22,
        curvature: 0.52,
        depth: 0.34,
        tilt: 6.5,
        distortion: 0.7,
        focusScale: 0.07,
        edgeFade: 0.46,
      },
      slide: {
        scale: 0.68,
        radius: 26,
        smoothing: 0.5,
        borderColor: "#95d5df",
        borderOpacity: 0.46,
        shadowOpacity: 0.54,
        shadowSoftness: 42,
      },
      background: { accent: "#dc4776" },
    },
  ),
  makeTheme(
    "alpine-silence",
    "Alpine Silence",
    "Drama · cold distance",
    "Sparse vertical movement through mineral daylight. Wide air, soft depth, almost no visual noise.",
    "polar-dawn",
    {
      motion: {
        axis: "vertical",
        direction: -1,
        speed: 0.14,
        flow: "arc",
        gap: 0.38,
        curvature: 0.18,
        depth: 0.24,
        tilt: 1.5,
        distortion: 0.16,
        focusScale: 0.06,
        edgeFade: 0.24,
      },
      slide: {
        scale: 0.72,
        radius: 24,
        smoothing: 0.46,
        borderColor: "#f1efe7",
        borderOpacity: 0.62,
        shadowOpacity: 0.2,
        shadowSoftness: 54,
      },
    },
  ),
  makeTheme(
    "ritual-ember",
    "Ritual Ember",
    "Myth · ceremonial dark",
    "A patient orbit through black velvet and an eclipsed ring. Formal, tactile, and slightly dangerous.",
    "velvet-eclipse",
    {
      motion: {
        axis: "vertical",
        direction: 1,
        speed: 0.12,
        flow: "cylinder",
        gap: 0.34,
        curvature: 0.64,
        depth: 0.44,
        tilt: 7,
        distortion: 0.46,
        focusScale: 0.1,
        edgeFade: 0.5,
      },
      slide: {
        scale: 0.65,
        radius: 12,
        smoothing: 0.24,
        borderWidth: 2,
        borderColor: "#b89562",
        borderOpacity: 0.58,
        shadowOpacity: 0.58,
        shadowSoftness: 52,
      },
      background: { accent: "#b66a38" },
    },
  ),
  makeTheme(
    "ocean-memory",
    "Ocean Memory",
    "Coming-of-age · submerged",
    "Blue depth, slow refraction, and frames drifting past like memories that will not hold still.",
    "deep-sea",
    {
      motion: {
        axis: "horizontal",
        direction: -1,
        speed: 0.18,
        flow: "ribbon",
        gap: 0.18,
        curvature: 0.4,
        depth: 0.32,
        tilt: 3.2,
        distortion: 0.52,
        focusScale: 0.12,
        edgeFade: 0.5,
      },
      slide: {
        scale: 0.76,
        radius: 44,
        smoothing: 0.68,
        borderColor: "#c6edf2",
        borderOpacity: 0.42,
        shadowOpacity: 0.22,
        shadowSoftness: 64,
      },
    },
  ),
  makeTheme(
    "daybreak-comedy",
    "Daybreak Comedy",
    "Comedy · bright timing",
    "Clean, quick movement in pale diffuse light. Buoyant without turning into confetti.",
    "moon-milk",
    {
      motion: {
        axis: "horizontal",
        direction: 1,
        speed: 0.48,
        flow: "straight",
        gap: 0.14,
        curvature: 0.08,
        depth: 0.08,
        tilt: 1.2,
        distortion: 0.12,
        focusScale: 0.05,
        edgeFade: 0.12,
      },
      slide: {
        scale: 0.7,
        radius: 34,
        smoothing: 0.6,
        borderWidth: 2,
        borderColor: "#242321",
        borderOpacity: 0.28,
        shadowOpacity: 0.18,
        shadowSoftness: 28,
      },
      background: { accent: "#e2a25d" },
    },
  ),
];

export function getTheme(id: ThemeId): ThemePreset {
  return THEMES.find((theme) => theme.id === id) ?? THEMES[0]!;
}

export function applyTheme(current: StudioSettings, theme: ThemePreset): StudioSettings {
  return {
    ...structuredClone(theme.settings),
    // A theme owns the rendered atmosphere, including whether that atmosphere
    // is transparent. Preserve the user's canvas dimensions, but never carry a
    // stale transparency flag into an opaque theme.
    stage: {
      ...theme.settings.stage,
      width: current.stage.width,
      height: current.stage.height,
      transparent: theme.settings.background.style === "transparent",
    },
    output: { ...current.output },
    presenter: { ...current.presenter },
  };
}
